---
- hosts: all
  sudo: yes
  roles:
    - dockerhost
    - enable-consul-port
    - savagegus.consul
  vars:
    consul_is_ui: "true"
    consul_is_server: "true"
    consul_datacenter: "test"
    consul_bootstrap: "true"
    consul_node_name: "{{ inventory_hostname }}"
    consul_bind_address: "{{ ansible_eth1['ipv4']['address'] }}"
    consul_servers: ['10.11.0.100', '10.11.0.101', '10.11.0.102']
