---
- hosts: primary
  sudo: yes
  roles:
    - savagegus.consul
  vars:
    consul_is_server: true
    consul_datacenter: "test"
    consul_node_name: "{{ inventory_hostname }}"
    consul_bind_address: "{{ ansible_eth1['ipv4']['address'] }}"
    consul_is_ui: true
    consul_bootstrap: true
    consul_join_at_start: true
    consul_servers: ['11.11.0.100', '10.11.0.101', '10.11.0.102']
    nginx_remove_default: yes
    htpasswd:
      - name: admin
        users:
          - { name: admin, password: admin }
    nginx_sites:
      - id: consul
        add_webroot: no
        name: consul.local
        rules:
          - gzip
          - security
        auth:
          name: Consul
          file: admin

- hosts: secondary
  sudo: yes
  roles:
    - savagegus.consul
  vars:
    consul_is_server: true
    consul_datacenter: "test"
    consul_node_name: "{{ inventory_hostname }}"
    consul_bind_address: "{{ ansible_eth1['ipv4']['address'] }}"
    consul_join_at_start: true
    consul_servers: ['11.11.0.100', '10.11.0.101', '10.11.0.102']
